### ISSUE TITLE
extraction error

### ISSUE THREAD

**Issue by CaiYitao** [histolab/histolab#422]
### Discussed in https://github.com/histolab/histolab/discussions/420

<div type='discussions-op-text'>

<sup>Originally posted by **CaiYitao** July  6, 2022</sup>
Just tried out to extract GridTiler, but get the following error:
```
Traceback (most recent call last):
  File ~/miniconda3/envs/ml/lib/python3.9/site-packages/PIL/Image.py", line 669, in _repr_png_
    id(self),
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/PIL/Image.py", line 2307, in save
    :returns: A tuple containing bands.
KeyError: 'PNG'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/IPython/core/formatters.py", line 222, in catch_format_error
    r = method(self, *args, **kwargs)
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/IPython/core/formatters.py", line 343, in __call__
    return method()
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/PIL/Image.py", line 671, in _repr_png_
ValueError: Could not save to PNG for display

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1993, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/IPython/core/ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/IPython/core/ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "~/miniconda3/envs/ml/lib/python3.9/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```
Is it because my PIL library is not compatible with histolab?

my slide is in ".mrxs" format, I also tried to set suffix to .jpg but got same error
```
grid_tiles_extractor = GridTiler(
   tile_size=(512, 512),
   level=0,
   check_tissue=True, # default
   pixel_overlap=0, # default
   prefix="grid/", # save tiles in the "grid" subdirectory of slide's processed_path
   suffix=".jpg" 
)
```</div>

**Comment by CaiYitao** [comment]
Is this normal?
my slide is a ".mrxs" file
<img width="413" alt="image" src="https://user-images.githubusercontent.com/65641330/178227572-13c8115e-13f2-4a63-bff0-8924d5e493ac.png">

**Comment by ernestoarbitrio** [comment]
Hi @CaiYitao could you provide detailed info about:
- operating system
- python version
- histolab version
- PIL
- openslide
Thanks.

**Comment by CaiYitao** [comment]
Rocky Linux  8.6
python 3.9
histolab 0.5.1
PIL version 8.4  (also installed libiconv which installed together with 9.2 version)   
openslide 1.2

Thank you for your prompt reply!

**Comment by CaiYitao** [comment]
I also tried with another dataset which is ".svs" format
the timing is great but the grid is not complete
<img width="545" alt="image" src="https://user-images.githubusercontent.com/65641330/178257310-1f4a9cab-688f-4fe3-bec0-8ef4318aa715.png">

**Comment by ernestoarbitrio** [comment]
Hi @CaiYitao . We will respond ASAP, probably next week.

**Comment by CaiYitao** [comment]
Hi @ernestoarbitrio, Could we extract all the parts in one slide now?

**Comment by alessiamarcolini** [comment]
Hi @CaiYitao 

>  Could we extract all the parts in one slide now?

The result you're showing is compatible with the default tiling behavior, i.e., extracting tiles from the biggest tissue portion in the slide. This behavior is controlled by the parameter `extraction_mask` in the `locate_tiles` or `extract` method of the tiler, which has `histolab.masks.BiggestTissueBoxMask()` as default value.

Therefore, if you want to extract tiles from all the tissue found in the slide you need to instantiate the `histolab.masks.TissueMask` extraction mask and pass it to `extraction_mask`.

```python
from histolab.masks import TissueMask

# your code here

grid_tiles_extractor.locate_tiles(
        slide=slide,
        extraction_mask=TissueMask(),
        # your params
    )
```

**Comment by CaiYitao** [comment]
Hi @alessiamarcolini, 
Thank you very much for your prompt reply!
and this works!!! 

Did we find out the reason why it took a very long time for processing .mrxs file?

BTW, can we write the tiles as jpg? when I set the suffix= ".jpg" and extract the tiles.
It gave error like this:
```
--> 632     raise OSError(f"cannot write mode {im.mode} as JPEG") from e
    634 info = im.encoderinfo
    636 dpi = [round(x) for x in info.get("dpi", (0, 0))]

OSError: cannot write mode RGBA as JPEG
```


Thank you!
