### ISSUE TITLE
large_image.exceptions.TileSourceError

### ISSUE THREAD

**Issue by a1ecbennington** [histolab/histolab#691]
when I want to extract my WSI, an error occurred unexpectedly. Anyone can give me a hand please.
The error information is as follow: Traceback (most recent call last):
  File "D:\deeplearning\medical_classification\test.py", line 15, in <module>
    image_slide.show()
  File "C:\Users\86176\Anaconda3\lib\site-packages\histolab\slide.py", line 485, in show
    thumbnail = self.thumbnail
  File "C:\Users\86176\Anaconda3\lib\site-packages\histolab\slide.py", line 502, in thumbnail
    self._thumbnail_size, self.dimensions
  File "C:\Users\86176\Anaconda3\lib\site-packages\histolab\slide.py", line 694, in _thumbnail_size
    for s in self.dimensions
  File "C:\Users\86176\Anaconda3\lib\site-packages\histolab\slide.py", line 174, in dimensions
    return self._metadata["sizeX"], self._metadata["sizeY"]
  File "C:\Users\86176\Anaconda3\lib\site-packages\histolab\slide.py", line 565, in _metadata
    return self._tile_source.getMetadata()
  File "C:\Users\86176\Anaconda3\lib\site-packages\histolab\slide.py", line 718, in _tile_source
    source = large_image.getTileSource(self._path)
  File "C:\Users\86176\Anaconda3\lib\site-packages\large_image\tilesource\__init__.py", line 162, in getTileSource
    return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
  File "C:\Users\86176\Anaconda3\lib\site-packages\large_image\tilesource\__init__.py", line 150, in getTileSourceFromDict
    raise TileSourceError('No available tilesource for %s' % pathOrUri)
large_image.exceptions.TileSourceError: No available tilesource for E:/F155519-1.ndpi
The code is 
import histolab.tiler as tiler
from histolab.slide import Slide
image_path = "E:/F155519-1.ndpi"
processed_path = "E:/grid"
image_slide = Slide(path=image_path, processed_path=processed_path, use_largeimage=True)
tiles_extractor = tiler.GridTiler(
    tile_size=(512, 512),
    level=0,
    check_tissue=True,
    tissue_percent=80.0,
    prefix="grid/",
    suffix=".png"
)
image_slide.show()

**Comment by ernestoarbitrio** [comment]
Can you please tell which version of histolab are you using? Moreover, the latest version is not supporting (officially) windows anymore.
Anyway, at a first glance I see that you are specifying the url using `unix` based path format like:
```
image_path = "E:/F155519-1.ndpi"
processed_path = "E:/grid"
```
But IMHO windows OS uses `E:\....` with the backslashes.

Did you try to change it?

**Comment by a1ecbennington** [comment]
> Can you please tell which version of histolab are you using? Moreover, the latest version is not supporting (officially) windows anymore.你能告诉我你用的是哪个版本的historab吗?此外，最新版本不再支持(官方的)windows。 Anyway, at a first glance I see that you are specifying the url using `unix` based path format like:无论如何，乍一看，我看到你指定的url使用基于路径格式，如:
> 
> ```
> image_path = "E:/F155519-1.ndpi"
> processed_path = "E:/grid"
> ```
> 
> But IMHO windows OS uses `E:\....` with the backslashes.但我认为windows操作系统使用反斜杠。
> 
> Did you try to change it?你试过改变吗?

The version is 0.6.0. Actually, I am using Win11 and you have a point. I tried to rollback to 0.3.0 and it is working. Thank you very much.

**Comment by ernestoarbitrio** [comment]
np
